/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentski.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import studentski.model.Opomena;
import studentski.model.Student;
import studentski.pomocno.Pomocno;

/**
 *
 * @author Ivan
 */
public class PojedinostiOpomene extends javax.swing.JFrame {

    private Opomena opomena;
    private DateFormat df;
    private NumberFormat nf;
    private DecimalFormat decf;
    /**
     * Creates new form PojedinostiOpomene
     */
    public PojedinostiOpomene(Opomena opomena) {
        initComponents();
        this.opomena = opomena;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        nf=NumberFormat.getInstance(Pomocno.ZEMLJA);
        decf=(DecimalFormat) nf;
        decf.applyPattern(Pomocno.FORMAT_BROJA);
        df = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumIzdavanjaOpomene.setText(df.format(opomena.getIzdavanjeOpomene()));
        txtDatumIzdavanjaNeplacenogRacuna.setText(df.format(opomena.getRacun().getDatumIzdavanjaRacuna()));
        /*try{
            txtDatumUplateOpomene.setText(df.format(opomena.getDatumUplateOpomene()));
        }catch(Exception e){
            txtDatumUplateOpomene.setText("Opomena nije plaćena!");
        }*/
        if(opomena.isPlacenoNakonOpomene()){
            cmbPlaceno.setSelectedIndex(0);
        }else{
            cmbPlaceno.setSelectedIndex(1);
        }
        Student s = new Student();
        DefaultListModel<Student> model = new DefaultListModel<>();
        model.addElement(s = opomena.getRacun().getStudent());
        jList1.setModel(model);
        txtIznos.setText(decf.format(opomena.getRacun().getCijena() == null ? 500 : opomena.getRacun().getCijena()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDatumIzdavanjaOpomene = new javax.swing.JTextField();
        cmbPlaceno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        txtIznos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDatumIzdavanjaNeplacenogRacuna = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datum izdavanja opomene:");

        txtDatumIzdavanjaOpomene.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cmbPlaceno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Da", "Ne" }));
        cmbPlaceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlacenoActionPerformed(evt);
            }
        });

        jLabel2.setText("Opomena plaćena:");

        jLabel3.setText("Student:");

        jScrollPane1.setViewportView(jList1);

        jLabel5.setText("Iznos:");

        txtIznos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Datum izdavanja neplaćenog računa:");

        txtDatumIzdavanjaNeplacenogRacuna.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("KN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDatumIzdavanjaOpomene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(cmbPlaceno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtDatumIzdavanjaNeplacenogRacuna)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIznos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtDatumIzdavanjaNeplacenogRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtDatumIzdavanjaOpomene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cmbPlaceno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPlacenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlacenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPlacenoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPlaceno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<Student> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDatumIzdavanjaNeplacenogRacuna;
    private javax.swing.JTextField txtDatumIzdavanjaOpomene;
    private javax.swing.JTextField txtIznos;
    // End of variables declaration//GEN-END:variables
}
