/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentski.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import studentski.controller.Obrada;
import studentski.model.Paviljon;
import studentski.model.Soba;

/**
 *
 * @author Ivan
 */
public class SobeNova extends javax.swing.JFrame {
    
    private Obrada<Soba> obrada;
    private Paviljon paviljon;
    private Integer brojSobe;
    private Sobe prozor;

    /**
     * Creates new form SobeNova
     */
    public SobeNova(Paviljon paviljon, Sobe prozor) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.prozor=prozor;
        this.paviljon = paviljon;
        obrada = new Obrada<>();
        lblPaviljon.setText(paviljon.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBrojSobe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDodajNoviDom = new javax.swing.JButton();
        cmbBrojKreveta = new javax.swing.JComboBox<>();
        lblPaviljon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Paviljon:");

        jLabel2.setText("Broj sobe:");

        jLabel3.setText("Broj kreveta:");

        btnDodajNoviDom.setText("Dodaj novi");
        btnDodajNoviDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNoviDomActionPerformed(evt);
            }
        });

        cmbBrojKreveta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "1" }));
        cmbBrojKreveta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDodajNoviDom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbBrojKreveta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBrojSobe, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaviljon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaviljon, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBrojSobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbBrojKreveta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnDodajNoviDom)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajNoviDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNoviDomActionPerformed
        Soba soba = new Soba();
        soba = napuniSobu(soba);
        if(brojSobe == 0){
            JOptionPane.showMessageDialog(getRootPane(), "Neispravno unesen broj sobe!");
            return;
        }
        boolean kontrola = false;
        kontrola = provjeri(soba);
        if(!kontrola){
            return;
        }
        obrada.save(soba);
        JOptionPane.showMessageDialog(getRootPane(), "Unjeli ste novu sobu!");
        prozor.napuniSobe();
        dispose();
    }//GEN-LAST:event_btnDodajNoviDomActionPerformed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
     // TODO add your handling code here:
    }//GEN-LAST:event_none

   
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNoviDom;
    private javax.swing.JComboBox<String> cmbBrojKreveta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPaviljon;
    private javax.swing.JTextField txtBrojSobe;
    // End of variables declaration//GEN-END:variables

    private Soba napuniSobu(Soba soba) {
        soba.setPaviljon(paviljon);
        brojSobe = 1;
        try{
            soba.setBrojSobe(Integer.valueOf(txtBrojSobe.getText()));
        }catch(Exception e){
            soba.setBrojSobe(0);
            brojSobe = 0;
        }
        soba.setBrojKreveta(Integer.valueOf((String)cmbBrojKreveta.getSelectedItem()));
        return soba;
    }

    private boolean provjeri(Soba soba) {
        if(soba==null){
            JOptionPane.showMessageDialog(getRootPane(), "Neispravno unesena nova soba!");
            return false;
        }
        else if(soba.getBrojKreveta()==0){
            JOptionPane.showMessageDialog(getRootPane(), "Niste odabrali broj kreveta u sobi");
            return false;
        }
        else if(soba.getBrojSobe()<=0){
            JOptionPane.showMessageDialog(getRootPane(), "Neispravan broj sobe");
            return false;
        }
        else return true;
    }
}
