/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentski.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import studentski.controller.Obrada;
import studentski.model.Soba;
import studentski.model.StudentskiDom;
import studentski.pomocno.HibernateUtil;

/**
 *
 * @author Ivan
 */
public class SobeNova extends javax.swing.JFrame {
    
    private Obrada<Soba> obrada;
    private StudentskiDom studentskiDom;
    private Integer brojSobe;
    private Sobe prozor;

    /**
     * Creates new form SobeNova
     */
    public SobeNova(Sobe prozor) {
        initComponents();
        this.prozor=prozor;
        cmbStudentskiDomovi.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        obrada = new Obrada<>();
        napuniStudentske();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPaviljon = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtBrojSobe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDodajNoviDom = new javax.swing.JButton();
        cmbBrojKreveta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbStudentskiDomovi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Paviljon:");

        cmbPaviljon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "crveni", "plavi" }));

        jLabel2.setText("Broj sobe:");

        jLabel3.setText("Broj kreveta:");

        btnDodajNoviDom.setText("Dodaj novi");
        btnDodajNoviDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNoviDomActionPerformed(evt);
            }
        });

        cmbBrojKreveta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "1" }));

        jLabel5.setText("Spremi sobu u studentski dom:");

        cmbStudentskiDomovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudentskiDomoviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDodajNoviDom)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbBrojKreveta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPaviljon, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrojSobe)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(cmbStudentskiDomovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbStudentskiDomovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbPaviljon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBrojSobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbBrojKreveta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnDodajNoviDom)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajNoviDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNoviDomActionPerformed
        Soba soba = new Soba();
        brojSobe = 0;
        soba = napuniSobu(soba);
        if(brojSobe == 1){
            JOptionPane.showMessageDialog(getRootPane(), "Neispravno unesen broj sobe!");
            return;
        }
        boolean kontrola = false;
        kontrola = provjeri(soba);
        if(!kontrola){
            return;
        }
        obrada.save(soba);
        JOptionPane.showMessageDialog(getRootPane(), "Unjeli ste novu sobu!");
        prozor.napuniSobe();
        dispose();
    }//GEN-LAST:event_btnDodajNoviDomActionPerformed

    private void cmbStudentskiDomoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudentskiDomoviActionPerformed
        studentskiDom = (StudentskiDom)cmbStudentskiDomovi.getSelectedItem();
    }//GEN-LAST:event_cmbStudentskiDomoviActionPerformed

   
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNoviDom;
    private javax.swing.JComboBox<String> cmbBrojKreveta;
    private javax.swing.JComboBox<String> cmbPaviljon;
    private javax.swing.JComboBox<StudentskiDom> cmbStudentskiDomovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtBrojSobe;
    // End of variables declaration//GEN-END:variables

    private Soba napuniSobu(Soba soba) {
        soba.setPaviljon((String)cmbPaviljon.getSelectedItem());
        try{
            soba.setBrojSobe(Integer.parseInt(txtBrojSobe.getText()));
        }catch(Exception e){
            soba.setBrojSobe(0);
            brojSobe = 1;
        }
        soba.setBrojKreveta(Integer.parseInt((String)cmbBrojKreveta.getSelectedItem()));
        soba.setStudentskiDom(studentskiDom);
        return soba;
    }

    private void napuniStudentske() {
        DefaultComboBoxModel<StudentskiDom> model = new DefaultComboBoxModel<>();
        List<StudentskiDom> lista = HibernateUtil.getSession().createQuery(
            " from StudentskiDom a where a.obrisano=false").list();
        for (StudentskiDom studentskiDom : lista) {
            model.addElement(studentskiDom);
        }
        cmbStudentskiDomovi.setModel(model);
    }

    private boolean provjeri(Soba soba) {
        if(soba==null){
            JOptionPane.showMessageDialog(getRootPane(), "Neispravno unesena nova soba!");
            return false;
        }
        else if(soba.getStudentskiDom()==null){
            JOptionPane.showMessageDialog(getRootPane(), "Niste odabrali studentski dom");
            return false;
        }
        else if(soba.getPaviljon().trim().length()==0){
            JOptionPane.showMessageDialog(getRootPane(), "Nista odabrali paviljon");
            return false;
        }
        else if(soba.getBrojKreveta()==0){
            JOptionPane.showMessageDialog(getRootPane(), "Niste odabrali broj kreveta u sobi");
            return false;
        }
        else if(soba.getBrojSobe()<=0){
            JOptionPane.showMessageDialog(getRootPane(), "Neispravan broj sobe");
            return false;
        }
        else return true;
    }
}
